In [1]:
import pandas as pd

import numpy as np

data = pd.read_excel("Återbet.xlsx")

data = data[pd.to_numeric(data['OrderNo'], errors='coerce').notnull()]

data["OrderNo"] = data["OrderNo"].astype(int).replace('\.o', '', regex = True)

data["PriceIncVat"] = data["PriceIncVat"].astype(int).replace('\.o', '', regex = True)

data = data[["ProductName", "OrderNo", "PriceIncVat", "PriceExcVat", "Info"]]

data

,ProductName,OrderNo,PriceIncVat,PriceExcVat,Info
0,Guldkortet ÅA,594854,1599,1279.2,", Klarna, Digitalt"
1,Bonusåkband,594854,0,0.0,", Klarna, Hämta i park"
2,Bonusåkband,594874,0,0.0,", Klarna, Hämta i park"
3,Entré 7-64 web,594874,130,104.0,", Klarna, Hemleverans"
4,Guldkortet web,594874,1699,1359.2,", Klarna, Hemleverans"
5,Bonusentré,595567,0,0.0,", Klarna, Digitalt"
6,Bonusåkband,595567,0,0.0,", Klarna, Hämta i park"
7,Guldkortet web,595567,1699,1359.2,", Klarna, Hemleverans"
8,Guldkortet ÅA,597574,1599,1279.2,", Klarna, Digitalt"
9,Bonusentré,597574,0,0.0,", Klarna, Digitalt"
10,Bonusåkband,597574,0,0.0,", Klarna, Hämta i park"
11,Gröna Kortet web,598674,310,248.0,", Klarna, Hemleverans"
12,Gröna Kortet web,598674,310,248.0,", Klarna, Hemleverans"
13,Guldkortet web,598758,1699,1359.2,", Klarna, Hämta i park"
14,Bonusentré,598758,0,0.0,", Klarna, Digitalt"
15,Bonusåkband,598758,0,0.0,", Klarna, Hämta i park"
16,Guldkortet ÅA,600549,1599,1279.2,", Klarna, Digitalt"
17,Guldkortet ÅA,600549,1599,1279.2,", Klarna, Digitalt"
18,Guldkortet web,600638,1699,1359.2,", Klarna, Hämta i park"
20,NaN,8,13942,11153.6,NaN

In [3]:
data["Moms"] = data["PriceIncVat"]-data["PriceExcVat"]

In [4]:
data

data.dropna(subset=['ProductName'], inplace = True)

data["Konto"] = None

data

,ProductName,OrderNo,PriceIncVat,PriceExcVat,Info,Moms,Konto
0,Guldkortet ÅA,594854,1599,1279.2,", Klarna, Digitalt",319.8,None
1,Bonusåkband,594854,0,0.0,", Klarna, Hämta i park",0.0,None
2,Bonusåkband,594874,0,0.0,", Klarna, Hämta i park",0.0,None
3,Entré 7-64 web,594874,130,104.0,", Klarna, Hemleverans",26.0,None
4,Guldkortet web,594874,1699,1359.2,", Klarna, Hemleverans",339.8,None
5,Bonusentré,595567,0,0.0,", Klarna, Digitalt",0.0,None
6,Bonusåkband,595567,0,0.0,", Klarna, Hämta i park",0.0,None
7,Guldkortet web,595567,1699,1359.2,", Klarna, Hemleverans",339.8,None
8,Guldkortet ÅA,597574,1599,1279.2,", Klarna, Digitalt",319.8,None
9,Bonusentré,597574,0,0.0,", Klarna, Digitalt",0.0,None
10,Bonusåkband,597574,0,0.0,", Klarna, Hämta i park",0.0,None
11,Gröna Kortet web,598674,310,248.0,", Klarna, Hemleverans",62.0,None
12,Gröna Kortet web,598674,310,248.0,", Klarna, Hemleverans",62.0,None
13,Guldkortet web,598758,1699,1359.2,", Klarna, Hämta i park",339.8,None
14,Bonusentré,598758,0,0.0,", Klarna, Digitalt",0.0,None
15,Bonusåkband,598758,0,0.0,", Klarna, Hämta i park",0.0,None
16,Guldkortet ÅA,600549,1599,1279.2,", Klarna, Digitalt",319.8,None
17,Guldkortet ÅA,600549,1599,1279.2,", Klarna, Digitalt",319.8,None
18,Guldkortet web,600638,1699,1359.2,", Klarna, Hämta i park",339.8,None

In [5]:
data2 = data.copy()

data2

data2["Belopp"] = None

data2

,ProductName,OrderNo,PriceIncVat,PriceExcVat,Info,Moms,Konto,Belopp
0,Guldkortet ÅA,594854,1599,1279.2,", Klarna, Digitalt",319.8,None,None
1,Bonusåkband,594854,0,0.0,", Klarna, Hämta i park",0.0,None,None
2,Bonusåkband,594874,0,0.0,", Klarna, Hämta i park",0.0,None,None
3,Entré 7-64 web,594874,130,104.0,", Klarna, Hemleverans",26.0,None,None
4,Guldkortet web,594874,1699,1359.2,", Klarna, Hemleverans",339.8,None,None
5,Bonusentré,595567,0,0.0,", Klarna, Digitalt",0.0,None,None
6,Bonusåkband,595567,0,0.0,", Klarna, Hämta i park",0.0,None,None
7,Guldkortet web,595567,1699,1359.2,", Klarna, Hemleverans",339.8,None,None
8,Guldkortet ÅA,597574,1599,1279.2,", Klarna, Digitalt",319.8,None,None
9,Bonusentré,597574,0,0.0,", Klarna, Digitalt",0.0,None,None
10,Bonusåkband,597574,0,0.0,", Klarna, Hämta i park",0.0,None,None
11,Gröna Kortet web,598674,310,248.0,", Klarna, Hemleverans",62.0,None,None
12,Gröna Kortet web,598674,310,248.0,", Klarna, Hemleverans",62.0,None,None
13,Guldkortet web,598758,1699,1359.2,", Klarna, Hämta i park",339.8,None,None
14,Bonusentré,598758,0,0.0,", Klarna, Digitalt",0.0,None,None
15,Bonusåkband,598758,0,0.0,", Klarna, Hämta i park",0.0,None,None
16,Guldkortet ÅA,600549,1599,1279.2,", Klarna, Digitalt",319.8,None,None
17,Guldkortet ÅA,600549,1599,1279.2,", Klarna, Digitalt",319.8,None,None
18,Guldkortet web,600638,1699,1359.2,", Klarna, Hämta i park",339.8,None,None

In [6]:
data2["PriceIncVat"] = data2["PriceIncVat"]*-1

In [7]:
data2

,ProductName,OrderNo,PriceIncVat,PriceExcVat,Info,Moms,Konto,Belopp
0,Guldkortet ÅA,594854,-1599,1279.2,", Klarna, Digitalt",319.8,None,None
1,Bonusåkband,594854,0,0.0,", Klarna, Hämta i park",0.0,None,None
2,Bonusåkband,594874,0,0.0,", Klarna, Hämta i park",0.0,None,None
3,Entré 7-64 web,594874,-130,104.0,", Klarna, Hemleverans",26.0,None,None
4,Guldkortet web,594874,-1699,1359.2,", Klarna, Hemleverans",339.8,None,None
5,Bonusentré,595567,0,0.0,", Klarna, Digitalt",0.0,None,None
6,Bonusåkband,595567,0,0.0,", Klarna, Hämta i park",0.0,None,None
7,Guldkortet web,595567,-1699,1359.2,", Klarna, Hemleverans",339.8,None,None
8,Guldkortet ÅA,597574,-1599,1279.2,", Klarna, Digitalt",319.8,None,None
9,Bonusentré,597574,0,0.0,", Klarna, Digitalt",0.0,None,None
10,Bonusåkband,597574,0,0.0,", Klarna, Hämta i park",0.0,None,None
11,Gröna Kortet web,598674,-310,248.0,", Klarna, Hemleverans",62.0,None,None
12,Gröna Kortet web,598674,-310,248.0,", Klarna, Hemleverans",62.0,None,None
13,Guldkortet web,598758,-1699,1359.2,", Klarna, Hämta i park",339.8,None,None
14,Bonusentré,598758,0,0.0,", Klarna, Digitalt",0.0,None,None
15,Bonusåkband,598758,0,0.0,", Klarna, Hämta i park",0.0,None,None
16,Guldkortet ÅA,600549,-1599,1279.2,", Klarna, Digitalt",319.8,None,None
17,Guldkortet ÅA,600549,-1599,1279.2,", Klarna, Digitalt",319.8,None,None
18,Guldkortet web,600638,-1699,1359.2,", Klarna, Hämta i park",339.8,None,None

In [8]:
data2["Konto"] = "1570"

In [9]:
data2

,ProductName,OrderNo,PriceIncVat,PriceExcVat,Info,Moms,Konto,Belopp
0,Guldkortet ÅA,594854,-1599,1279.2,", Klarna, Digitalt",319.8,1570,None
1,Bonusåkband,594854,0,0.0,", Klarna, Hämta i park",0.0,1570,None
2,Bonusåkband,594874,0,0.0,", Klarna, Hämta i park",0.0,1570,None
3,Entré 7-64 web,594874,-130,104.0,", Klarna, Hemleverans",26.0,1570,None
4,Guldkortet web,594874,-1699,1359.2,", Klarna, Hemleverans",339.8,1570,None
5,Bonusentré,595567,0,0.0,", Klarna, Digitalt",0.0,1570,None
6,Bonusåkband,595567,0,0.0,", Klarna, Hämta i park",0.0,1570,None
7,Guldkortet web,595567,-1699,1359.2,", Klarna, Hemleverans",339.8,1570,None
8,Guldkortet ÅA,597574,-1599,1279.2,", Klarna, Digitalt",319.8,1570,None
9,Bonusentré,597574,0,0.0,", Klarna, Digitalt",0.0,1570,None
10,Bonusåkband,597574,0,0.0,", Klarna, Hämta i park",0.0,1570,None
11,Gröna Kortet web,598674,-310,248.0,", Klarna, Hemleverans",62.0,1570,None
12,Gröna Kortet web,598674,-310,248.0,", Klarna, Hemleverans",62.0,1570,None
13,Guldkortet web,598758,-1699,1359.2,", Klarna, Hämta i park",339.8,1570,None
14,Bonusentré,598758,0,0.0,", Klarna, Digitalt",0.0,1570,None
15,Bonusåkband,598758,0,0.0,", Klarna, Hämta i park",0.0,1570,None
16,Guldkortet ÅA,600549,-1599,1279.2,", Klarna, Digitalt",319.8,1570,None
17,Guldkortet ÅA,600549,-1599,1279.2,", Klarna, Digitalt",319.8,1570,None
18,Guldkortet web,600638,-1699,1359.2,", Klarna, Hämta i park",339.8,1570,None

In [10]:
data2["B"] = None
data2["C"]= None
data2["D"] = None
data2["E"] = None

In [11]:
data2 = data2[["Konto", "B", "C", "D", "E", "PriceIncVat", "OrderNo"]]

data2.columns = ["Konto", "B", "C", "D", "E","Belopp", "Referens"]

data2

   Konto     B     C     D     E  Belopp  Referens
0   1570  None  None  None  None   -1599    594854
1   1570  None  None  None  None       0    594854
2   1570  None  None  None  None       0    594874
3   1570  None  None  None  None    -130    594874
4   1570  None  None  None  None   -1699    594874
5   1570  None  None  None  None       0    595567
6   1570  None  None  None  None       0    595567
7   1570  None  None  None  None   -1699    595567
8   1570  None  None  None  None   -1599    597574
9   1570  None  None  None  None       0    597574
10  1570  None  None  None  None       0    597574
11  1570  None  None  None  None    -310    598674
12  1570  None  None  None  None    -310    598674
13  1570  None  None  None  None   -1699    598758
14  1570  None  None  None  None       0    598758
15  1570  None  None  None  None       0    598758
16  1570  None  None  None  None   -1599    600549
17  1570  None  None  None  None   -1599    600549
18  1570  None  None  None  None   -1699    600638

In [12]:
data

,ProductName,OrderNo,PriceIncVat,PriceExcVat,Info,Moms,Konto
0,Guldkortet ÅA,594854,1599,1279.2,", Klarna, Digitalt",319.8,None
1,Bonusåkband,594854,0,0.0,", Klarna, Hämta i park",0.0,None
2,Bonusåkband,594874,0,0.0,", Klarna, Hämta i park",0.0,None
3,Entré 7-64 web,594874,130,104.0,", Klarna, Hemleverans",26.0,None
4,Guldkortet web,594874,1699,1359.2,", Klarna, Hemleverans",339.8,None
5,Bonusentré,595567,0,0.0,", Klarna, Digitalt",0.0,None
6,Bonusåkband,595567,0,0.0,", Klarna, Hämta i park",0.0,None
7,Guldkortet web,595567,1699,1359.2,", Klarna, Hemleverans",339.8,None
8,Guldkortet ÅA,597574,1599,1279.2,", Klarna, Digitalt",319.8,None
9,Bonusentré,597574,0,0.0,", Klarna, Digitalt",0.0,None
10,Bonusåkband,597574,0,0.0,", Klarna, Hämta i park",0.0,None
11,Gröna Kortet web,598674,310,248.0,", Klarna, Hemleverans",62.0,None
12,Gröna Kortet web,598674,310,248.0,", Klarna, Hemleverans",62.0,None
13,Guldkortet web,598758,1699,1359.2,", Klarna, Hämta i park",339.8,None
14,Bonusentré,598758,0,0.0,", Klarna, Digitalt",0.0,None
15,Bonusåkband,598758,0,0.0,", Klarna, Hämta i park",0.0,None
16,Guldkortet ÅA,600549,1599,1279.2,", Klarna, Digitalt",319.8,None
17,Guldkortet ÅA,600549,1599,1279.2,", Klarna, Digitalt",319.8,None
18,Guldkortet web,600638,1699,1359.2,", Klarna, Hämta i park",339.8,None

In [13]:
data["Konto"] = None

In [14]:
data

,ProductName,OrderNo,PriceIncVat,PriceExcVat,Info,Moms,Konto
0,Guldkortet ÅA,594854,1599,1279.2,", Klarna, Digitalt",319.8,None
1,Bonusåkband,594854,0,0.0,", Klarna, Hämta i park",0.0,None
2,Bonusåkband,594874,0,0.0,", Klarna, Hämta i park",0.0,None
3,Entré 7-64 web,594874,130,104.0,", Klarna, Hemleverans",26.0,None
4,Guldkortet web,594874,1699,1359.2,", Klarna, Hemleverans",339.8,None
5,Bonusentré,595567,0,0.0,", Klarna, Digitalt",0.0,None
6,Bonusåkband,595567,0,0.0,", Klarna, Hämta i park",0.0,None
7,Guldkortet web,595567,1699,1359.2,", Klarna, Hemleverans",339.8,None
8,Guldkortet ÅA,597574,1599,1279.2,", Klarna, Digitalt",319.8,None
9,Bonusentré,597574,0,0.0,", Klarna, Digitalt",0.0,None
10,Bonusåkband,597574,0,0.0,", Klarna, Hämta i park",0.0,None
11,Gröna Kortet web,598674,310,248.0,", Klarna, Hemleverans",62.0,None
12,Gröna Kortet web,598674,310,248.0,", Klarna, Hemleverans",62.0,None
13,Guldkortet web,598758,1699,1359.2,", Klarna, Hämta i park",339.8,None
14,Bonusentré,598758,0,0.0,", Klarna, Digitalt",0.0,None
15,Bonusåkband,598758,0,0.0,", Klarna, Hämta i park",0.0,None
16,Guldkortet ÅA,600549,1599,1279.2,", Klarna, Digitalt",319.8,None
17,Guldkortet ÅA,600549,1599,1279.2,", Klarna, Digitalt",319.8,None
18,Guldkortet web,600638,1699,1359.2,", Klarna, Hämta i park",339.8,None

In [15]:
for i in data:
    if "Hämta i park" in i:
        data.at[index, 'new_column'] = new_value

In [16]:
data

,ProductName,OrderNo,PriceIncVat,PriceExcVat,Info,Moms,Konto
0,Guldkortet ÅA,594854,1599,1279.2,", Klarna, Digitalt",319.8,None
1,Bonusåkband,594854,0,0.0,", Klarna, Hämta i park",0.0,None
2,Bonusåkband,594874,0,0.0,", Klarna, Hämta i park",0.0,None
3,Entré 7-64 web,594874,130,104.0,", Klarna, Hemleverans",26.0,None
4,Guldkortet web,594874,1699,1359.2,", Klarna, Hemleverans",339.8,None
5,Bonusentré,595567,0,0.0,", Klarna, Digitalt",0.0,None
6,Bonusåkband,595567,0,0.0,", Klarna, Hämta i park",0.0,None
7,Guldkortet web,595567,1699,1359.2,", Klarna, Hemleverans",339.8,None
8,Guldkortet ÅA,597574,1599,1279.2,", Klarna, Digitalt",319.8,None
9,Bonusentré,597574,0,0.0,", Klarna, Digitalt",0.0,None
10,Bonusåkband,597574,0,0.0,", Klarna, Hämta i park",0.0,None
11,Gröna Kortet web,598674,310,248.0,", Klarna, Hemleverans",62.0,None
12,Gröna Kortet web,598674,310,248.0,", Klarna, Hemleverans",62.0,None
13,Guldkortet web,598758,1699,1359.2,", Klarna, Hämta i park",339.8,None
14,Bonusentré,598758,0,0.0,", Klarna, Digitalt",0.0,None
15,Bonusåkband,598758,0,0.0,", Klarna, Hämta i park",0.0,None
16,Guldkortet ÅA,600549,1599,1279.2,", Klarna, Digitalt",319.8,None
17,Guldkortet ÅA,600549,1599,1279.2,", Klarna, Digitalt",319.8,None
18,Guldkortet web,600638,1699,1359.2,", Klarna, Hämta i park",339.8,None

In [17]:
data["Referens"] = None

data

data["Konto"] = "2976"

In [18]:
data.loc[data['ProductName'].str.contains('Guldkortet'), 'Referens'] = '3056/110'
data.loc[data['ProductName'].str.contains('Gröna Kortet'), 'Referens'] = '3018/110'
data.loc[data['ProductName'].str.contains('Åkband'), 'Referens'] = '3051/110'
data.loc[data['ProductName'].str.contains('Paketentré'), 'Referens'] = '3001/110'
data.loc[data['ProductName'].str.contains('House'), 'Referens'] = '3059/110'
data.loc[data['ProductName'].str.contains('Rab'), 'Referens'] = '3011/110'
data.loc[data['ProductName'].str.contains('House'), 'Konto'] = "2978"
data.loc[data['Info'].str.contains('Hämta'), 'Konto'] = "2813"

data

,ProductName,OrderNo,PriceIncVat,PriceExcVat,Info,Moms,Konto,Referens
0,Guldkortet ÅA,594854,1599,1279.2,", Klarna, Digitalt",319.8,2976,3056/110
1,Bonusåkband,594854,0,0.0,", Klarna, Hämta i park",0.0,2813,None
2,Bonusåkband,594874,0,0.0,", Klarna, Hämta i park",0.0,2813,None
3,Entré 7-64 web,594874,130,104.0,", Klarna, Hemleverans",26.0,2976,None
4,Guldkortet web,594874,1699,1359.2,", Klarna, Hemleverans",339.8,2976,3056/110
5,Bonusentré,595567,0,0.0,", Klarna, Digitalt",0.0,2976,None
6,Bonusåkband,595567,0,0.0,", Klarna, Hämta i park",0.0,2813,None
7,Guldkortet web,595567,1699,1359.2,", Klarna, Hemleverans",339.8,2976,3056/110
8,Guldkortet ÅA,597574,1599,1279.2,", Klarna, Digitalt",319.8,2976,3056/110
9,Bonusentré,597574,0,0.0,", Klarna, Digitalt",0.0,2976,None
10,Bonusåkband,597574,0,0.0,", Klarna, Hämta i park",0.0,2813,None
11,Gröna Kortet web,598674,310,248.0,", Klarna, Hemleverans",62.0,2976,3018/110
12,Gröna Kortet web,598674,310,248.0,", Klarna, Hemleverans",62.0,2976,3018/110
13,Guldkortet web,598758,1699,1359.2,", Klarna, Hämta i park",339.8,2813,3056/110
14,Bonusentré,598758,0,0.0,", Klarna, Digitalt",0.0,2976,None
15,Bonusåkband,598758,0,0.0,", Klarna, Hämta i park",0.0,2813,None
16,Guldkortet ÅA,600549,1599,1279.2,", Klarna, Digitalt",319.8,2976,3056/110
17,Guldkortet ÅA,600549,1599,1279.2,", Klarna, Digitalt",319.8,2976,3056/110
18,Guldkortet web,600638,1699,1359.2,", Klarna, Hämta i park",339.8,2813,3056/110

In [19]:
data["2610"] = None

data["2630"] = None

data["Belopp"] = None

data.loc[data['Konto'].str.contains('2976'), '2610'] = data["Moms"]
data.loc[data['Konto'].str.contains('2978'), '2630'] = data["Moms"]

data.loc[data['Konto'].str.contains('2976'), 'Belopp'] = data["PriceExcVat"]
data.loc[data['Konto'].str.contains('2978'), 'Belopp'] = data["PriceExcVat"]
data.loc[data['Konto'].str.contains('2813'), 'Belopp'] = data["PriceIncVat"]

data

,ProductName,OrderNo,PriceIncVat,PriceExcVat,Info,Moms,Konto,Referens,2610,2630,Belopp
0,Guldkortet ÅA,594854,1599,1279.2,", Klarna, Digitalt",319.8,2976,3056/110,319.8,None,1279.2
1,Bonusåkband,594854,0,0.0,", Klarna, Hämta i park",0.0,2813,None,None,None,0
2,Bonusåkband,594874,0,0.0,", Klarna, Hämta i park",0.0,2813,None,None,None,0
3,Entré 7-64 web,594874,130,104.0,", Klarna, Hemleverans",26.0,2976,None,26,None,104
4,Guldkortet web,594874,1699,1359.2,", Klarna, Hemleverans",339.8,2976,3056/110,339.8,None,1359.2
5,Bonusentré,595567,0,0.0,", Klarna, Digitalt",0.0,2976,None,0,None,0
6,Bonusåkband,595567,0,0.0,", Klarna, Hämta i park",0.0,2813,None,None,None,0
7,Guldkortet web,595567,1699,1359.2,", Klarna, Hemleverans",339.8,2976,3056/110,339.8,None,1359.2
8,Guldkortet ÅA,597574,1599,1279.2,", Klarna, Digitalt",319.8,2976,3056/110,319.8,None,1279.2
9,Bonusentré,597574,0,0.0,", Klarna, Digitalt",0.0,2976,None,0,None,0
10,Bonusåkband,597574,0,0.0,", Klarna, Hämta i park",0.0,2813,None,None,None,0
11,Gröna Kortet web,598674,310,248.0,", Klarna, Hemleverans",62.0,2976,3018/110,62,None,248
12,Gröna Kortet web,598674,310,248.0,", Klarna, Hemleverans",62.0,2976,3018/110,62,None,248
13,Guldkortet web,598758,1699,1359.2,", Klarna, Hämta i park",339.8,2813,3056/110,None,None,1699
14,Bonusentré,598758,0,0.0,", Klarna, Digitalt",0.0,2976,None,0,None,0
15,Bonusåkband,598758,0,0.0,", Klarna, Hämta i park",0.0,2813,None,None,None,0
16,Guldkortet ÅA,600549,1599,1279.2,", Klarna, Digitalt",319.8,2976,3056/110,319.8,None,1279.2
17,Guldkortet ÅA,600549,1599,1279.2,", Klarna, Digitalt",319.8,2976,3056/110,319.8,None,1279.2
18,Guldkortet web,600638,1699,1359.2,", Klarna, Hämta i park",339.8,2813,3056/110,None,None,1699

In [20]:
Moms_25 = data["2610"].sum()
Moms_6 = data["2630"].sum()

data.loc[-1] = [None, None, None, None, None, None, "2610", None, None, None, Moms_25]
data.loc[-2] = [None, None, None, None, None, None, "2630", None, None, None, Moms_6]



data

,ProductName,OrderNo,PriceIncVat,PriceExcVat,Info,Moms,Konto,Referens,2610,2630,Belopp
0,Guldkortet ÅA,594854,1599,1279.2,", Klarna, Digitalt",319.8,2976,3056/110,319.8,None,1279.2
1,Bonusåkband,594854,0,0.0,", Klarna, Hämta i park",0.0,2813,None,None,None,0
2,Bonusåkband,594874,0,0.0,", Klarna, Hämta i park",0.0,2813,None,None,None,0
3,Entré 7-64 web,594874,130,104.0,", Klarna, Hemleverans",26.0,2976,None,26,None,104
4,Guldkortet web,594874,1699,1359.2,", Klarna, Hemleverans",339.8,2976,3056/110,339.8,None,1359.2
5,Bonusentré,595567,0,0.0,", Klarna, Digitalt",0.0,2976,None,0,None,0
6,Bonusåkband,595567,0,0.0,", Klarna, Hämta i park",0.0,2813,None,None,None,0
7,Guldkortet web,595567,1699,1359.2,", Klarna, Hemleverans",339.8,2976,3056/110,339.8,None,1359.2
8,Guldkortet ÅA,597574,1599,1279.2,", Klarna, Digitalt",319.8,2976,3056/110,319.8,None,1279.2
9,Bonusentré,597574,0,0.0,", Klarna, Digitalt",0.0,2976,None,0,None,0
10,Bonusåkband,597574,0,0.0,", Klarna, Hämta i park",0.0,2813,None,None,None,0
11,Gröna Kortet web,598674,310,248.0,", Klarna, Hemleverans",62.0,2976,3018/110,62,None,248
12,Gröna Kortet web,598674,310,248.0,", Klarna, Hemleverans",62.0,2976,3018/110,62,None,248
13,Guldkortet web,598758,1699,1359.2,", Klarna, Hämta i park",339.8,2813,3056/110,None,None,1699
14,Bonusentré,598758,0,0.0,", Klarna, Digitalt",0.0,2976,None,0,None,0
15,Bonusåkband,598758,0,0.0,", Klarna, Hämta i park",0.0,2813,None,None,None,0
16,Guldkortet ÅA,600549,1599,1279.2,", Klarna, Digitalt",319.8,2976,3056/110,319.8,None,1279.2
17,Guldkortet ÅA,600549,1599,1279.2,", Klarna, Digitalt",319.8,2976,3056/110,319.8,None,1279.2
18,Guldkortet web,600638,1699,1359.2,", Klarna, Hämta i park",339.8,2813,3056/110,None,None,1699
-1,None,None,None,NaN,None,NaN,2610,None,None,None,2108.8
-2,None,None,None,NaN,None,NaN,2630,None,None,None,0

In [21]:
data["B"] = None
data["C"]= None
data["D"] = None
data["E"] = None

data

,ProductName,OrderNo,PriceIncVat,PriceExcVat,Info,Moms,Konto,Referens,2610,2630,Belopp,B,C,D,E
0,Guldkortet ÅA,594854,1599,1279.2,", Klarna, Digitalt",319.8,2976,3056/110,319.8,None,1279.2,None,None,None,None
1,Bonusåkband,594854,0,0.0,", Klarna, Hämta i park",0.0,2813,None,None,None,0,None,None,None,None
2,Bonusåkband,594874,0,0.0,", Klarna, Hämta i park",0.0,2813,None,None,None,0,None,None,None,None
3,Entré 7-64 web,594874,130,104.0,", Klarna, Hemleverans",26.0,2976,None,26,None,104,None,None,None,None
4,Guldkortet web,594874,1699,1359.2,", Klarna, Hemleverans",339.8,2976,3056/110,339.8,None,1359.2,None,None,None,None
5,Bonusentré,595567,0,0.0,", Klarna, Digitalt",0.0,2976,None,0,None,0,None,None,None,None
6,Bonusåkband,595567,0,0.0,", Klarna, Hämta i park",0.0,2813,None,None,None,0,None,None,None,None
7,Guldkortet web,595567,1699,1359.2,", Klarna, Hemleverans",339.8,2976,3056/110,339.8,None,1359.2,None,None,None,None
8,Guldkortet ÅA,597574,1599,1279.2,", Klarna, Digitalt",319.8,2976,3056/110,319.8,None,1279.2,None,None,None,None
9,Bonusentré,597574,0,0.0,", Klarna, Digitalt",0.0,2976,None,0,None,0,None,None,None,None
10,Bonusåkband,597574,0,0.0,", Klarna, Hämta i park",0.0,2813,None,None,None,0,None,None,None,None
11,Gröna Kortet web,598674,310,248.0,", Klarna, Hemleverans",62.0,2976,3018/110,62,None,248,None,None,None,None
12,Gröna Kortet web,598674,310,248.0,", Klarna, Hemleverans",62.0,2976,3018/110,62,None,248,None,None,None,None
13,Guldkortet web,598758,1699,1359.2,", Klarna, Hämta i park",339.8,2813,3056/110,None,None,1699,None,None,None,None
14,Bonusentré,598758,0,0.0,", Klarna, Digitalt",0.0,2976,None,0,None,0,None,None,None,None
15,Bonusåkband,598758,0,0.0,", Klarna, Hämta i park",0.0,2813,None,None,None,0,None,None,None,None
16,Guldkortet ÅA,600549,1599,1279.2,", Klarna, Digitalt",319.8,2976,3056/110,319.8,None,1279.2,None,None,None,None
17,Guldkortet ÅA,600549,1599,1279.2,", Klarna, Digitalt",319.8,2976,3056/110,319.8,None,1279.2,None,None,None,None
18,Guldkortet web,600638,1699,1359.2,", Klarna, Hämta i park",339.8,2813,3056/110,None,None,1699,None,None,None,None
-1,None,None,None,NaN,None,NaN,2610,None,None,None,2108.8,None,None,None,None
-2,None,None,None,NaN,None,NaN,2630,None,None,None,0,None,None,None,None

In [22]:
data = data[["Konto", "B", "C", "D", "E", "Belopp", "Referens"]]

data

    Konto     B     C     D     E  Belopp  Referens
 0   2976  None  None  None  None  1279.2  3056/110
 1   2813  None  None  None  None       0      None
 2   2813  None  None  None  None       0      None
 3   2976  None  None  None  None     104      None
 4   2976  None  None  None  None  1359.2  3056/110
 5   2976  None  None  None  None       0      None
 6   2813  None  None  None  None       0      None
 7   2976  None  None  None  None  1359.2  3056/110
 8   2976  None  None  None  None  1279.2  3056/110
 9   2976  None  None  None  None       0      None
 10  2813  None  None  None  None       0      None
 11  2976  None  None  None  None     248  3018/110
 12  2976  None  None  None  None     248  3018/110
 13  2813  None  None  None  None    1699  3056/110
 14  2976  None  None  None  None       0      None
 15  2813  None  None  None  None       0      None
 16  2976  None  None  None  None  1279.2  3056/110
 17  2976  None  None  None  None  1279.2  3056/110
 18  2813  None  None  None  None    1699  3056/110
-1   2610  None  None  None  None  2108.8      None
-2   2630  None  None  None  None       0      None

In [26]:
frames = [data, data2]

data3 = pd.concat(frames)

data3 = data3[data3.Belopp != 0]

data3

    Konto     B     C     D     E  Belopp  Referens
 0   2976  None  None  None  None  1279.2  3056/110
 3   2976  None  None  None  None     104      None
 4   2976  None  None  None  None  1359.2  3056/110
 7   2976  None  None  None  None  1359.2  3056/110
 8   2976  None  None  None  None  1279.2  3056/110
 11  2976  None  None  None  None     248  3018/110
 12  2976  None  None  None  None     248  3018/110
 13  2813  None  None  None  None    1699  3056/110
 16  2976  None  None  None  None  1279.2  3056/110
 17  2976  None  None  None  None  1279.2  3056/110
 18  2813  None  None  None  None    1699  3056/110
-1   2610  None  None  None  None  2108.8      None
 0   1570  None  None  None  None   -1599    594854
 3   1570  None  None  None  None    -130    594874
 4   1570  None  None  None  None   -1699    594874
 7   1570  None  None  None  None   -1699    595567
 8   1570  None  None  None  None   -1599    597574
 11  1570  None  None  None  None    -310    598674
 12  1570  None  None  None  None    -310    598674
 13  1570  None  None  None  None   -1699    598758
 16  1570  None  None  None  None   -1599    600549
 17  1570  None  None  None  None   -1599    600549
 18  1570  None  None  None  None   -1699    600638

In [24]:
data3["Belopp"] = data3["Belopp"].astype(float).replace('\.o', '', regex = True)

data3["Konto"] = data3["Konto"].astype(int).replace('\.o', '', regex = True)

data3.to_csv('Återbetalning.csv', index=False, header=False, sep = ";")